name: CI

on:
  pull_request:
  push:

jobs:
  verify-bashutils:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: install bats-core
        run: |
          ./helper.sh reqs
      - name: bump up version
        run: ./helper.sh bump_up_version
      - name: build bashutils
        run: ./helper.sh build
      - name: bash syntax check
        run: bash -n bashutils-template.sh && bash -n bashutils
      - name: run bats tests
        run: ./helper.sh test
      - name: Create release artifacts
        run: ./helper.sh create_release_artifacts
      - name: Create GitHub release
        id: create_release
        if: github.ref == 'refs/heads/main'
        run: ./helper.sh create_release
        env: 
          # RELEASE_DRAFT: "true"
          GH_TOKEN: ${{ github.token }}
      - name: 'commit and push updated files'
        if: github.ref == 'refs/heads/main' && steps.create_release.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .version bashutils bashutils.checksum
          git diff --cached --quiet || git commit -m "auto: update files [skip ci]"
          git push

